var knofeherbastya = document.querySelector('.knofeherbastya').value 
var knofeherhuszar = document.querySelector('.knofeherhuszar').value
var knofeherfuto = document.querySelector('.knofeherfuto').value
var kfeherbastya = document.querySelector('.kfeherbastya').value
var kfeherhuszar = document.querySelector('.kfeherhuszar').value
var kfeherfuto = document.querySelector('.kfeherfuto').value
var feherkiralyno = document.querySelector('.feherkiralyno').value
var feherkiraly = document.querySelector('.feherkiraly').value
var knofeketebastya = document.querySelector('.knofeketebastya').value
var knofeketehuszar = document.querySelector('.knofeketehuszar').value
var knofeketefuto = document.querySelector('.knofeketefuto').value
var kfeketebastya = document.querySelector('.kfeketebastya').value
var kfeketehuszar = document.querySelector('.kfeketehuszar').value
var kfeketefuto = document.querySelector('.kfeketefuto').value
var feketekiralyno = document.querySelector('.feketekiralyno').value
var feketekiraly = document.querySelector('.feketekiraly').value

console.log(knofeketebastya)

function click(){
    alert(feketekiralyno)
}
function RejtettOldalonBtn(){
    if  (feketekiraly == 'feketekiraly'){
        document.getElementById('valami21').onclick=semmi()
    } else {
        console.log('kfenakfnaepf')
    }
}
function valami(){
    alert('Eljutottál az első lépéshez a pénthez jutás felé.')
}
function semmi(){
    alert('semmifakfh')
}