knofeherbastya = document.querySelector('.knofeherbastya').src
knofeherhuszar = document.querySelector('.knofeherhuszar').src
knofeherfuto = document.querySelector('.knofeherfuto').src
kfeherbastya = document.querySelector('.kfeherbastya').src
kfeherhuszar = document.querySelector('.kfeherhuszar').src
kfeherfuto = document.querySelector('.kfeherfuto').src
feherkiralyno = document.querySelector('.feherkiralyno').src
feherkiraly = document.querySelector('.feherkiraly').src
knofeketebastya = document.querySelector('.knofeketebastya').src
knofeketehuszar = document.querySelector('.knofeketehuszar').src
knofeketefuto = document.querySelector('.knofeketefuto').src
kfeketebastya = document.querySelector('.kfeketebastya').src
kfeketehuszar = document.querySelector('.kfeketehuszar').src
kfeketefuto = document.querySelector('.kfeketefuto').src
feketekiralyno = document.querySelector('.feketekiralyno').src
feketekiraly = document.querySelector('.feketekiraly').src

function click2(){
    alert(feketekiralyno)
}
function RejtettOldalonBtn(){
    alert('Eljutottál az első lépéshez a pénthez jutás felé. ')
}
